spring:
  application:
  name: springboot-service-demo

  data:
    mongodb:
      host: localhost
      port: 27017
      database: testdb

server:
  port: 8080
  servlet:
    context-path: /api/spring-boot-course